services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: "sqlite+aiosqlite:///data.db"
    depends_on:
      - db
    command:
      - "poetry"
      - "run"
      - "pytest"

  db:
    image: mysql:8
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: durov

volumes:
  mysql_data:
